### ISSUE TITLE
only half of triangles being renderered from .blend file

### ISSUE THREAD

**Issue by m0ppers** [Marzac/le3d#21]
Created a simple sphere with blender...unfortunately only half the triangles are rendered.

The same happens to me when using the standard cube of blender. My .obj file is looking different. Is there a special flag when exporting that is currently mandatory?

Here is my file (really just a standard sphere 16x16)

https://www.file-upload.net/download-13132510/sphere.blend.html

After copy pasting the .obj from the examples the cube is looking fine.

![grafik](https://user-images.githubusercontent.com/819421/40138110-48447cb2-594c-11e8-975c-98a158930535.png)

**Comment by Marzac** [comment]
Here are the flags I use with Blender:
![flags](https://user-images.githubusercontent.com/1386049/40144289-675dc966-595e-11e8-9139-e7d122e034ec.png)

Please note that there is at now a severe limitation in the obj file importer code. Texture coordinates MUST be exported, normal coordinates MUST NOT be exported. The parser is not flexible enough and I am going to fix it very soon (and include the obj exporter too).

**Comment by m0ppers** [comment]
That worked :D Thank you :)

Also the engine requires textures. I was thinking that I could create primitives with a fixed color using cpp only without having to use blender but I got hard crashes here:

https://github.com/Marzac/le3d/blob/master/engine/rasterizer_float.cpp#L97

So I went back to blender. No problem for now :)

**Comment by Marzac** [comment]
I have opened issues 15 & 16 for this problem.
