### ISSUE TITLE
Spelling: LePlan shouldn't it be LePlain?

### ISSUE THREAD

**Issue by gwald** [Marzac/le3d#31]
Plan, ie project management plan
Plain, ie plain is a flat, sweeping landmass
Plane, ie airplane

**Comment by Marzac** [comment]
Hi @gwald.

I think you're right.
I still need to make a good pass on the project objects nomenclature, before it's too late (when it's actually being used by other developers for their own projects). Plan is the French word actually.

I think LePlane is the right one:
https://en.wikipedia.org/wiki/Plane_(geometry)

Please tell me if you find some other names / terms that sound weird to you.

All the best.

**Comment by Marzac** [comment]
Corrected and tested.
Thank you @gwald / Mike.
